# WasmRuntime.jl — WASM island loader runtime
#
# Provides shared JS helpers for loading and initializing WASM island modules.
# Included once per page alongside ReactiveRuntime.jl.
#
# Pattern: Leptos-style thin JS glue. Each island's WASM module is instantiated
# with a shared import object pattern. DOM mutation functions are scoped per-island.
#
# API:
#   window.__tw.dom(island) → DOM import functions scoped to island element
#   window.__tw.io(island)  → full import object for WebAssembly.instantiate

"""
    therapy_wasm_runtime_js() -> String

Return the shared WASM island runtime JavaScript (~300 bytes minified).

Provides `window.__tw` with helpers used by per-island WASM loaders:
- `__tw.dom(el)` — creates DOM import functions (set_text, set_attr, set_display)
  scoped to an island element. These are provided to WASM as imported functions.
- `__tw.io(el)` — creates the complete import object for `WebAssembly.instantiate()`,
  including Math.pow (for WasmTarget type registry) and DOM helpers.

The per-island JS loader (generated by _generate_island_wasm) calls:
```javascript
var _io = __tw.io(island);
WebAssembly.instantiate(wasmBytes, _io).then(function(result) { ... });
```
"""
function therapy_wasm_runtime_js()::String
    return """
(function(){
window.__tw={
dom:function(el){return{
set_text:function(hk,v){var n=el.querySelector('[data-hk=\"'+hk+'\"]');if(n)n.textContent=String(v);},
set_attr:function(hk,a,v){var n=el.querySelector('[data-hk=\"'+hk+'\"]');if(n)n.setAttribute(a,String(v));},
set_display:function(hk,s){var n=el.querySelector('[data-hk=\"'+hk+'\"]');if(n)n.style.display=s?'':'none';}
};},
io:function(el){return{Math:{pow:Math.pow},dom:__tw.dom(el)};}
};
})();"""
end
